### ISSUE TITLE
Depend on timely 0.2

### ISSUE THREAD

**Issue by aepsil0n** [frankmcsherry/differential-dataflow#71]
Playing around with `differential-dataflow` atm, I realized that you are depending on timely's git repository rather than the 0.2 version crates.io. Is there a specific reason for that, i.e., would it be harder to quickly iterate on new features, if you'd depend on 0.2?

From a user's perspective, it's always nicer to depend on a stable-ish version, only updating once in a while.

**Comment by frankmcsherry** [comment]
Historically, I think it has been about being able to tweak something in timely and then do some experimentation that involves more than one person. Timely hasn't changed too much, so it hasn't seemed too painful to point at the repo.

In a perfect world, I'm guessing you'd prefer to have more regular differential dataflow crates.io drops, so that there was a stability guarantee throughout, is that right? Or are you playing around with the code itself and how it works? My sense is that, given that these are all research projects, it would be best to compartmentalize the stability guarantees to crates.io, and let the github projects flop around as appropriate. Ideally not breaking regularly, but not promising anything either.

Is this a concrete problem for you, or more of an aesthetic issue?

**Comment by aepsil0n** [comment]
It's not a concrete problem, I was just asking to gauge how experimental you consider this. Also by now I have come to the conclusion that `differential-dataflow` is probably the wrong abstraction for the application domain I have in mind anyway (computational fluid dynamics). So I'm moving back to using timely directly. I guess, it's just that I'm not used any more to Rust crates dependening on git repositories ;)

So I'll close this for now.

**Comment by frankmcsherry** [comment]
Cool, well definitely give a shout if things I'm / we're doing are making your life hard. It's a trade-off between doing new things and remaining helpful to anyone quietly using timely / differential (I have no idea who is using it :)).

**Comment by aepsil0n** [comment]
Just started to use it after having tried MPI bindings for the same task and timely is much nicer to use and to test, as there is no global state mess going on.

But thanks, I will definitely keep shouting out, if I come across things.
